version: '3'
services:
  app:
    container_name: szsk_yiyan
    image: szsk968/yiyan:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./public/:/app/public/
    depends_on:
      - redis
    restart: always

  redis:
    container_name: custom_redis
    image: redis
    command: ["redis-server"]
    restart: always